-- Mockwebsite database schema
-- Canonical source of truth: supabase/migrations/*.sql
--
-- The project now uses timestamped Supabase migrations so fresh and existing
-- environments share one reproducible schema. Do not apply this legacy snapshot
-- directly. Run the migrations in order with the Supabase CLI/CI pipeline.
--
-- The current schema includes:
-- profiles, exam catalog/stages/subjects/topics/sections,
-- question batches/questions/options/versions/validation/reviews/quality metrics,
-- test blueprints/templates/attempts/answers/events/results,
-- performance statistics, user preferences, admin roles and question reports.
